//! Shared LVS data-plane rendering for the IPSec load balancer.
//!
//! The `ip nat` table that hash-distributes customer IKE/ESP across the VPN
//! concentrators is rendered by TWO binaries:
//!   - `ipsecpulse` at boot (initial render), and
//!   - `ipsecscale` at runtime (re-render when the VPN ASG membership changes).
//!
//! To guarantee they produce BYTE-IDENTICAL rules -- in particular the SAME
//! jhash `seed` on all three protocol rules, without which proto-50 / UDP-500 /
//! UDP-4500 from one source IP hash to DIFFERENT concentrators at N>1 and IKE
//! splits across nodes (Architecture Decision #1) -- the renderer lives here,
//! in one place both depend on. Do NOT duplicate it.

/// Fixed jhash seed shared by all three PREROUTING rules. Changing this splits
/// every in-flight tunnel across nodes at the next rehash; never vary it per rule.
pub const JHASH_SEED: &str = "0xa5a5a5a5";

/// VPN concentrator subnets whose return traffic is SNAT'd out eth0.
pub const VPN_SUBNETS: &str = "172.16.49.0/24, 172.16.50.0/24";

/// Render the complete `ip nat` table for the LVS nodes.
///
/// * `instance_id`   -- for the file header comment only.
/// * `secondary_ip`  -- the fixed customer-facing VIP (eth0 secondary). Both the
///   PREROUTING DNAT scope (`ip daddr <secondary_ip>`) and the POSTROUTING SNAT
///   source. Stable across EIP movements.
/// * `vpn_ips`       -- private IPs of the live VPN concentrators, numerically
///   sorted by the caller for stable jhash map indices.
///
/// Uses inline anonymous maps (no `type integer` named map, no `$VARIABLE` in
/// mod position) to avoid nftables 1.0+ compatibility issues. The PREROUTING
/// rules are scoped to the customer VIP so they never hijack a concentrator-
/// INITIATED outbound IKE transiting this node (P2).
pub fn render_ipsec_nat(instance_id: &str, secondary_ip: &str, vpn_ips: &[String]) -> String {
	let ts = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ");
	let n  = vpn_ips.len();
	let mut out = String::new();

	out.push_str(&format!(
		"# ipsec-nat.nft -- generated for {instance_id}\n\
		 # Generated    : {ts}\n\
		 # DO NOT EDIT  -- regenerated by ipsecpulse (boot) and ipsecscale (VPN pool changes).\n\
		 # VPN backends : {n}\n\n",
	));

	out.push_str("table ip nat {\n");

	// PREROUTING: hash src IP -> VPN concentrator.
	out.push_str("\tchain PREROUTING {\n");
	out.push_str("\t\ttype nat hook prerouting priority dstnat; policy accept;\n");
	if n == 0 {
		out.push_str("\t\t# No VPN backends yet -- ipsecscale will update this file.\n");
	} else {
		let entries: String = vpn_ips.iter()
			.enumerate()
			.map(|(i, ip)| format!("{i} : {ip}"))
			.collect::<Vec<_>>()
			.join(", ");
		let map = format!("{{ {entries} }}");
		for rule in [
			format!("ip daddr {secondary_ip} ip protocol 50 dnat ip to jhash ip saddr mod {n} seed {JHASH_SEED} map {map}"),
			format!("ip daddr {secondary_ip} ip protocol udp udp dport 500 dnat ip to jhash ip saddr mod {n} seed {JHASH_SEED} map {map}"),
			format!("ip daddr {secondary_ip} ip protocol udp udp dport 4500 dnat ip to jhash ip saddr mod {n} seed {JHASH_SEED} map {map}"),
		] {
			out.push_str(&format!("\t\t{rule}\n"));
		}
	}
	out.push_str("\t}\n\n");

	// POSTROUTING: SNAT return traffic from VPN concentrators to the VIP.
	out.push_str("\tchain POSTROUTING {\n");
	out.push_str("\t\ttype nat hook postrouting priority srcnat; policy accept;\n");
	out.push_str(&format!(
		"\t\toifname \"eth0\" ip saddr {{ {VPN_SUBNETS} }} snat to {secondary_ip}\n"
	));
	out.push_str("\t}\n");
	out.push_str("}\n");

	out
}
